[D 161106 01:02:39 server:81] Init library with [/data/books/library/]
[D 161106 01:02:39 server:82] Init AuthDB  with [sqlite:////data/books/tornado.db]
[D 161106 01:02:39 server:83] Init Static  with [/data/code/my-calibre-server/v2/static]
[W 161106 01:15:17 web:1971] 405 CONNECT 163mx02.mxmail.netease.com:25 (36.229.232.92) 0.64ms
[W 161106 01:24:59 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.2057932365385659 (115.239.228.202) 0.46ms
[D 161106 01:43:12 base_handlers:71] Query User [None]
[D 161106 01:43:12 base_handlers:72] Query admin_user [None]
[E 161106 01:43:12 web:1548] Uncaught exception GET / (218.6.56.154)
    HTTPServerRequest(protocol='http', host='119.29.106.164:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='218.6.56.154', headers={'Accept-Language': 'zh-cn', 'Accept': '*/*', 'User-Agent': 'Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)', 'Host': '119.29.106.164:8080', 'Referer': 'http://119.29.106.164:8080/', 'Cache-Control': 'no-cache', 'Content-Type': 'application/x-www-form-urlencoded'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 01:43:12 web:1971] 500 GET / (218.6.56.154) 61.82ms
[W 161106 02:11:35 web:1971] 404 GET http://123.249.29.201:43210/?rands=_86968937005233201568560 (61.157.96.112) 0.64ms
[W 161106 02:11:35 web:1971] 404 GET http://50.117.86.106/?rands=_1488673594611578141605516 (61.157.96.112) 0.49ms
[W 161106 02:11:35 web:1971] 404 GET http://www.baidu.com/?rands=_22304311561682501026771468 (61.157.96.112) 0.46ms
[W 161106 02:26:45 web:1971] 404 GET http://www.google.com/reader/about/ (91.236.75.4) 0.44ms
[W 161106 02:43:33 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.1698166998864156 (115.239.228.202) 0.46ms
[W 161106 03:19:01 web:1971] 404 GET http://www.baidu.com/cache/global/img/gs.gif (80.82.78.38) 0.76ms
[W 161106 03:22:04 web:1971] 404 GET http://www.baidu.com/?rands=_98554135209189363299144 (61.157.96.112) 0.41ms
[W 161106 03:22:05 web:1971] 404 GET http://123.249.29.201:43210/?rands=_130447447504298701344480 (61.157.96.112) 0.42ms
[W 161106 03:22:05 web:1971] 404 GET http://50.117.86.106/?rands=_1736761974410720501556864 (61.157.96.112) 0.55ms
[W 161106 03:32:14 web:1971] 404 POST /command.php (189.218.173.113) 0.51ms
[W 161106 03:32:15 web:1971] 404 GET /language/Swedish${IFS}&&echo${IFS}610cker>qt&&tar${IFS}/string.js (189.218.173.113) 0.45ms
[W 161106 03:32:15 web:1971] 404 GET /../../../../../../../mnt/mtd/qt (189.218.173.113) 0.45ms
[W 161106 04:02:34 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.9384832049038869 (115.239.228.202) 0.47ms
[W 161106 04:56:54 web:1971] 404 GET http://www.baidu.com/cache/global/img/gs.gif (94.102.49.174) 0.37ms
[W 161106 05:20:59 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.4108443642697566 (115.239.228.202) 0.42ms
[W 161106 05:24:33 web:1971] 404 GET http://www.sogou.com/?rands=_52085421002869202360400 (61.157.96.110) 0.49ms
[W 161106 05:24:33 web:1971] 404 GET http://www.haosou.com/?rands=_1101645995416617243296592 (61.157.96.110) 0.45ms
[W 161106 05:24:33 web:1971] 404 GET http://23.251.55.38/?rands=_918013623017115122650920 (61.157.96.110) 0.43ms
[W 161106 05:48:13 web:1971] 404 GET http://123.249.29.201:43210/?rands=_145084442801240650164464 (61.157.96.112) 0.43ms
[W 161106 05:48:14 web:1971] 404 GET http://50.117.86.106/?rands=_95951581721442034236756 (61.157.96.112) 0.45ms
[W 161106 05:48:14 web:1971] 404 GET http://www.baidu.com/?rands=_814288916422934343258684 (61.157.96.112) 0.64ms
[W 161106 05:58:55 web:1971] 404 GET http://www.baidu.com/favicon.ico (123.59.70.63) 0.48ms
[D 161106 06:21:58 base_handlers:71] Query User [None]
[D 161106 06:21:58 base_handlers:72] Query admin_user [None]
[E 161106 06:21:58 web:1548] Uncaught exception GET / (115.236.128.14)
    HTTPServerRequest(protocol='http', host='127.0.0.1', method='GET', uri='/', version='HTTP/1.0', remote_ip='115.236.128.14', headers={})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 06:21:58 web:1971] 500 GET / (115.236.128.14) 59.62ms
[W 161106 06:21:58 web:1971] 405 OPTIONS / (115.236.128.14) 0.70ms
[I 161106 06:21:58 http1connection:253] Malformed HTTP message from 115.236.128.14: Malformed HTTP version in HTTP Request-Line: 'RTSP/1.0'
[W 161106 06:21:58 web:1971] 404 GET /nice%20ports%2C/Tri%6Eity.txt%2ebak (115.236.128.14) 0.41ms
[I 161106 06:21:58 http1connection:253] Malformed HTTP message from 115.236.128.14: Malformed HTTP headers: '\ngoogle.com\x00PGET / HTTP/1.0\r\n\r\n'
[I 161106 06:22:08 http1connection:253] Malformed HTTP message from 115.236.128.14: Malformed HTTP request line
[D 161106 06:30:54 base_handlers:71] Query User [None]
[D 161106 06:30:54 base_handlers:72] Query admin_user [None]
[E 161106 06:30:54 web:1548] Uncaught exception GET / (101.226.103.146)
    HTTPServerRequest(protocol='http', host='119.29.106.164:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='101.226.103.146', headers={'Connection': 'TE, close', 'Te': 'deflate,gzip;q=0.3', 'Host': '119.29.106.164:8080', 'User-Agent': 'libwww-perl/6.04'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 06:30:54 web:1971] 500 GET / (101.226.103.146) 59.60ms
[D 161106 06:30:55 base_handlers:71] Query User [None]
[D 161106 06:30:55 base_handlers:72] Query admin_user [None]
[E 161106 06:30:55 web:1548] Uncaught exception GET / (101.226.103.146)
    HTTPServerRequest(protocol='http', host='119.29.106.164:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='101.226.103.146', headers={'Connection': 'TE, close', 'Te': 'deflate,gzip;q=0.3', 'Host': '119.29.106.164:8080', 'User-Agent': 'libwww-perl/6.04'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 06:30:55 web:1971] 500 GET / (101.226.103.146) 57.02ms
[D 161106 06:30:55 base_handlers:71] Query User [None]
[D 161106 06:30:55 base_handlers:72] Query admin_user [None]
[E 161106 06:30:55 web:1548] Uncaught exception GET / (101.226.103.146)
    HTTPServerRequest(protocol='http', host='119.29.106.164:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='101.226.103.146', headers={'Connection': 'TE, close', 'Te': 'deflate,gzip;q=0.3', 'Host': '119.29.106.164:8080', 'User-Agent': 'libwww-perl/6.04'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 06:30:55 web:1971] 500 GET / (101.226.103.146) 52.57ms
[W 161106 06:39:20 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.6159044483722314 (115.239.228.202) 0.44ms
[D 161106 07:37:03 base_handlers:71] Query User [None]
[D 161106 07:37:03 base_handlers:72] Query admin_user [None]
[E 161106 07:37:03 web:1548] Uncaught exception GET / (121.199.70.200)
    HTTPServerRequest(protocol='http', host='119.10.29.102:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='121.199.70.200', headers={'Host': '119.10.29.102:8080'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 07:37:03 web:1971] 500 GET / (121.199.70.200) 61.93ms
[W 161106 07:58:11 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.0520052320983777 (115.239.228.202) 0.49ms
[W 161106 08:06:34 web:1971] 404 GET http://104.216.4.228:25643/?rands=_2144714757003586952544480 (104.216.4.228) 0.43ms
[D 161106 08:31:04 base_handlers:71] Query User [None]
[D 161106 08:31:04 base_handlers:72] Query admin_user [None]
[E 161106 08:31:04 web:1548] Uncaught exception GET / (183.60.48.110)
    HTTPServerRequest(protocol='http', host='119.29.106.164:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='183.60.48.110', headers={'Connection': 'TE, close', 'Te': 'deflate,gzip;q=0.3', 'Host': '119.29.106.164:8080', 'User-Agent': 'libwww-perl/6.04'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 08:31:04 web:1971] 500 GET / (183.60.48.110) 59.41ms
[W 161106 08:59:55 web:1971] 404 GET http://50.117.86.106/?rands=_11280264017067122505568 (61.157.96.112) 0.44ms
[W 161106 08:59:55 web:1971] 404 GET http://123.249.29.201:43210/?rands=_1030287603220435042093280 (61.157.96.112) 0.44ms
[W 161106 08:59:55 web:1971] 404 GET http://www.baidu.com/?rands=_1212033510012821583252960 (61.157.96.112) 0.55ms
[W 161106 09:16:52 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.4384034147057918 (115.239.228.202) 0.41ms
[W 161106 09:50:12 web:1971] 404 GET http://www.baidu.com/cache/global/img/gs.gif (163.172.173.62) 0.38ms
[D 161106 10:35:26 base_handlers:71] Query User [None]
[D 161106 10:35:26 base_handlers:72] Query admin_user [None]
[E 161106 10:35:26 web:1548] Uncaught exception GET / (222.186.134.126)
    HTTPServerRequest(protocol='http', host='119.29.106.164:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='222.186.134.126', headers={'Host': '119.29.106.164:8080', 'User-Agent': 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)', 'Accept': '*/*', 'Cache-Control': 'no-cache'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 10:35:26 web:1971] 500 GET / (222.186.134.126) 56.85ms
[W 161106 10:35:30 web:1971] 404 GET http://www.baidu.com/?rands=_1576860649613401154682656 (61.157.96.112) 0.54ms
[W 161106 10:35:30 web:1971] 404 GET http://50.117.86.106/?rands=_1396249123243965907297680 (61.157.96.112) 0.72ms
[W 161106 10:35:30 web:1971] 404 GET http://123.249.29.201:43210/?rands=_1612225167017681252498880 (61.157.96.112) 0.61ms
[W 161106 10:36:30 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.1287639460124700 (115.239.228.202) 0.51ms
[D 161106 12:02:32 base_handlers:71] Query User [None]
[D 161106 12:02:32 base_handlers:72] Query admin_user [None]
[E 161106 12:02:32 web:1548] Uncaught exception GET / (101.226.35.225)
    HTTPServerRequest(protocol='http', host='119.29.106.164:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='101.226.35.225', headers={'Accept-Encoding': 'gzip,deflate', 'Host': '119.29.106.164:8080', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.76 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://119.29.106.164:8080/', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Cookie': 'xx=xxx'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 12:02:32 web:1971] 500 GET / (101.226.35.225) 66.55ms
[D 161106 12:02:32 base_handlers:71] Query User [None]
[D 161106 12:02:32 base_handlers:72] Query admin_user [None]
[E 161106 12:02:32 web:1548] Uncaught exception GET / (101.226.35.225)
    HTTPServerRequest(protocol='http', host='119.29.106.164:8080', method='GET', uri='/', version='HTTP/1.1', remote_ip='101.226.35.225', headers={'Accept-Encoding': 'gzip, deflate', 'Host': '119.29.106.164:8080', 'Connection': 'keep-alive', 'Accept': '*/*', 'User-Agent': 'python-requests/2.11.1'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/code/my-calibre-server/v2/handlers/book_handlers.py", line 100, in get
        return self.html_page('index.html', vars())
      File "/data/code/my-calibre-server/v2/handlers/base_handlers.py", line 143, in html_page
        if not request.user.avatar:
    AttributeError: 'NoneType' object has no attribute 'avatar'
[E 161106 12:02:32 web:1971] 500 GET / (101.226.35.225) 60.82ms
[W 161106 12:23:47 web:1971] 404 GET http://testp3.pospr.waw.pl/testproxy.php (91.196.50.33) 0.35ms
[W 161106 13:02:24 web:1971] 404 GET http://50.117.86.106/?rands=_2058711025609605764917868 (61.157.96.112) 0.42ms
[W 161106 13:02:24 web:1971] 404 GET http://www.baidu.com/?rands=_1622536345614832853492 (61.157.96.112) 0.66ms
[W 161106 13:13:49 web:1971] 404 GET http://zc.qq.com/cgi-bin/common/attr?id=260714&r=0.6822570053402195 (115.239.228.202) 0.64ms
